namespace SpriteKind {
    export const hostileProjectile = SpriteKind.create()
    export const shopItem = SpriteKind.create()
    export const Regnbåge = SpriteKind.create()
    export const svärd = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.shopItem, function (sprite, otherSprite) {
    if (controller.A.isPressed()) {
        if (spelare.overlapsWith(multiSkott)) {
            if (info.score() >= 40) {
                antal_skott = 3
                sprites.destroy(multiSkott)
                info.changeScoreBy(-40)
            }
        } else if (spelare.overlapsWith(rainbow)) {
            if (info.score() >= 60) {
                sprites.destroy(rainbow)
                info.changeScoreBy(-60)
                regnbåge_tillgänglig += 1
            }
        } else {
            if (spelare.overlapsWith(heal)) {
                if (info.score() >= 20) {
                    sprites.destroy(heal)
                    info.changeScoreBy(-20)
                    spelare_HP.value += 100
                }
            }
        }
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile1`, function (sprite, location) {
    bana = 2
    tiles.setCurrentTilemap(tilemap`level33`)
    spelare.setImage(img`
        f f f f f f f f f f f 
        f f f f f f f f f f f 
        f f f f f f f f f 2 f 
        f 2 2 2 f f f f 2 2 f 
        f f f 2 2 f f 2 2 f f 
        f f 1 c 2 2 2 2 c 1 f 
        f f f 1 f 2 2 f 1 f f 
        f f f f f f f f f f f 
        f f f f f f f f f f f 
        f e f f f f f f f f f 
        f f e e e e e e e f f 
        f f f f e e e f f f f 
        f f f f f e f f f f f 
        f f f f f f f f f f f 
        f f f f f f f f f f f 
        f f f f f f f f f f f 
        `)
    spelare.ay = 250
    controller.moveSprite(spelare, 100, 0)
})
function atack () {
    attack_regnbåge = sprites.create(img`
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 5 5 5 5 5 5 5 5 5 5 5 5 5 2 2 
        2 5 4 4 4 4 4 4 4 4 4 4 4 5 2 2 
        2 5 4 2 2 2 2 2 2 2 2 2 4 5 2 2 
        2 5 4 2 a a a a a a a 2 4 5 2 2 
        2 5 4 2 a 8 8 8 8 8 a 2 4 5 2 2 
        2 5 4 2 a 8 6 6 6 8 a 2 4 5 2 2 
        2 5 4 2 a 8 6 9 6 8 a 2 4 5 2 2 
        2 5 4 2 a 8 6 6 6 8 a 2 4 5 2 2 
        2 5 4 2 a 8 8 8 8 8 a 2 4 5 2 2 
        2 5 4 2 a a a a a a a 2 4 5 2 2 
        2 5 4 2 2 2 2 2 2 2 2 2 4 5 2 2 
        2 5 4 4 4 4 4 4 4 4 4 4 4 5 2 2 
        2 5 5 5 5 5 5 5 5 5 5 5 5 5 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        `, SpriteKind.Regnbåge)
    tiles.placeOnTile(attack_regnbåge, tiles.getTileLocation(spelare.tilemapLocation().column, spelare.tilemapLocation().row))
    for (let index = 0; index <= 15; index++) {
        attack_regnbåge.changeScale(1, ScaleAnchor.Middle)
        pause(100)
    }
    regnbåge_tillgänglig += -1
    sprites.destroy(attack_regnbåge)
}
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bana == 3) {
        animation.runImageAnimation(
        spelare,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . . f f f f 2 2 f f f f . . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f f 2 f e f . . 
            . . f f f 2 f e e 2 2 f f f . . 
            . . f e 2 f f e e 2 f e e f . . 
            . f f e f f e e e f e e e f f . 
            . f f e e e e e e e e e e f f . 
            . . . f e e e e e e e e f . . . 
            . . . e f f f f f f f f 4 e . . 
            . . . 4 f 2 2 2 2 2 e d d 4 . . 
            . . . e f f f f f f e e 4 . . . 
            . . . . f f f . . . . . . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . f f f f f 2 2 f f f f f . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e 2 f 2 f f 2 f 2 e f . . 
            . . f f f 2 2 e e 2 2 f f f . . 
            . f f e f 2 f e e f 2 f e f f . 
            . f e e f f e e e e f e e e f . 
            . . f e e e e e e e e e e f . . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 4 4 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f e e e e f f . . . . 
            . . . f e e e f f e e e f . . . 
            . . . f f f f 2 2 f f f f . . . 
            . . f f e 2 e 2 2 e 2 e f f . . 
            . . f e f 2 f f f 2 f 2 e f . . 
            . . f f f 2 2 e e f 2 f f f . . 
            . . f e e f 2 e e f f 2 e f . . 
            . f f e e e f e e e f f e f f . 
            . f f e e e e e e e e e e f f . 
            . . . f e e e e e e e e f . . . 
            . . e 4 f f f f f f f f e . . . 
            . . 4 d d e 2 2 2 2 2 f 4 . . . 
            . . . 4 e e f f f f f f e . . . 
            . . . . . . . . . f f f . . . . 
            `],
        100,
        false
        )
        if (controller.A.isPressed()) {
            controller.moveSprite(spelare, 0, 0)
            if (spelare.isHittingTile(CollisionDirection.Left)) {
            	
            } else {
                svärd.setImage(img`
                    ................
                    ........c.......
                    ........cc......
                    ........cc......
                    ........ccc.....
                    ........cdc.....
                    ........cdc.....
                    .......ccddc....
                    .......cdddc....
                    .......cdddcc...
                    .......cddddc...
                    .......cddddc...
                    .......cddddc...
                    .......cdddcc...
                    .......cdddc....
                    .......cdddc....
                    .......cddcc....
                    .......cddc.....
                    ......ffffff....
                    ......ffffff....
                    ........ee......
                    ........ee......
                    ........ee......
                    ........ee......
                    .......ffff.....
                    .......ffff.....
                    `)
                svärd.setPosition(spelare.x, spelare.y - 22)
            }
            pause(100)
            svärd.y += 8
            pause(100)
            svärd.y += -8
            pause(100)
            svärd.setImage(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `)
        }
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    if (shop == 1) {
        shop = 0
        sprites.destroyAllSpritesOfKind(SpriteKind.shopItem)
        respawn()
    }
    if (bana == 1) {
        if (regnbåge_tillgänglig >= 1) {
            atack()
        }
    }
})
function respawn () {
    tiles.setCurrentTilemap(tilemap`level10`)
    tiles.placeOnTile(spelare, tiles.getTileLocation(14, 33))
    spelare.setImage(img`
        .......11..........
        .f.f..1111..f.f....
        .f2f.111111.f2f....
        .f2f.115511.f2f....
        .f2f.111111.f2f....
        .fff.115511.fff....
        .fff.111111.fff....
        .ffff111111ffff....
        .ffff115511ffff....
        .ffff211112ffff....
        ...ff111111ff......
        ....f111111f.......
        .....111111........
        ....11111111.......
        ...112222221.......
        .....222222........
        ....22222222.......
        ....22222222.......
        ...2222222222......
        `)
}
function impossible () {
    if (bana == 1) {
        enemyList = [
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy),
        sprites.create(img`
            ..........................
            ..........................
            ..........................
            ...fcfcfcfcfcfcfcfcfcfc...
            ...fffcfcfcfcfcfcfcfcfcc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ...ffffffffffffffffffffc..
            ...ccfcfcfcfcfcfcfcfcfcf..
            ....cfcfcfcfcfcfcfcfcfcf..
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            ..........................
            `, SpriteKind.Enemy)
        ]
        for (let value of enemyList) {
            enemyStatusBar = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
            value.setPosition(xoffset, 0)
            value.vy = 20
            xoffset += 26
            aliveList.push(value)
            enemyStatusBar.attachToSprite(value)
            value.setFlag(SpriteFlag.GhostThroughWalls, true)
        }
        xoffset = 22
    }
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bana == 1) {
        projectile = sprites.createProjectileFromSprite(img`
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            2 
            `, spelare, 0, -50)
        if (antal_skott == 3) {
            projektil2 = sprites.createProjectileFromSprite(img`
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                `, spelare, 0, -50)
            projektil2.setPosition(projectile.x + 10, projectile.y)
            projektil3 = sprites.createProjectileFromSprite(img`
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                2 
                `, spelare, 0, -50)
            projektil3.setPosition(projectile.x - 10, projectile.y)
        }
    } else if (bana == 3) {
    	
    } else {
        if (spelare.isHittingTile(CollisionDirection.Bottom)) {
            spelare.setVelocity(0, -100)
        }
    }
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bana == 3) {
        animation.runImageAnimation(
        spelare,
        [img`
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e e f f . . . . 
            . . . f 2 2 2 e d d 4 . . . . . 
            . . . f 2 2 2 e d d e . . . . . 
            . . . f 5 5 4 f e e f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . . f f f . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d e e e e e f . . . 
            . . . f e 4 e d d 4 f . . . . . 
            . . . f 2 2 e d d e f . . . . . 
            . . f f 5 5 f e e f f f . . . . 
            . . f f f f f f f f f f . . . . 
            . . . f f f . . . f f . . . . . 
            `,img`
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e e f f . . . . 
            . . . f 2 2 2 e d d 4 . . . . . 
            . . . f 2 2 2 e d d e . . . . . 
            . . . f 5 5 4 f e e f . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . . . . f f f . . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . f f f f f f . . . . . . 
            . . . f 2 f e e e e f f . . . . 
            . . f 2 2 2 f e e e e f f . . . 
            . . f e e e e f f e e e f . . . 
            . f e 2 2 2 2 e e f f f f . . . 
            . f 2 e f f f f 2 2 2 e f . . . 
            . f f f e e e f f f f f f f . . 
            . f e e 4 4 f b e 4 4 e f f . . 
            . . f e d d f 1 4 d 4 e e f . . 
            . . . f d d d d 4 e e e f . . . 
            . . . f e 4 4 4 e d d 4 . . . . 
            . . . f 2 2 2 2 e d d e . . . . 
            . . f f 5 5 4 4 f e e f . . . . 
            . . f f f f f f f f f f . . . . 
            . . . f f f . . . f f . . . . . 
            `],
        100,
        false
        )
        if (controller.A.isPressed()) {
            controller.moveSprite(spelare, 0, 0)
            if (spelare.isHittingTile(CollisionDirection.Left)) {
            	
            } else {
                svärd.setImage(img`
                    ..........................
                    ..........................
                    ..........................
                    ..........................
                    ..........................
                    ..........................
                    ..................ff......
                    .......cccccccccccff....ff
                    .cccccccddddddddddffeeeeff
                    ..cccdddddddddddddffeeeeff
                    ....cccdddddddddccff....ff
                    .......cccdddcccc.ff......
                    .........ccccc............
                    ..........................
                    ..........................
                    ..........................
                    `)
                svärd.setPosition(spelare.x - 22, spelare.y + 3)
            }
            pause(100)
            svärd.x += -8
            pause(100)
            svärd.x += 8
            pause(100)
            svärd.setImage(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `)
        }
    }
})
sprites.onOverlap(SpriteKind.hostileProjectile, SpriteKind.Player, function (sprite, otherSprite) {
    spelare_HP.value += -2
    sprites.destroy(sprite)
})
info.onCountdownEnd(function () {
    shop = 1
    tiles.setCurrentTilemap(tilemap`level30`)
    bana = 0
    for (let value of aliveList) {
        sprites.destroy(value)
    }
    aliveList = []
    spelare.setImage(img`
        . . . . . . . . . . . c c c c . 
        . . . . c c c c c c c c f f c . 
        . . . c c f f f c c f f f f c . 
        . . c c f f f f f f f f f c c . 
        . . c f f f f f f f f f f c . . 
        . . c f f f f f f f f f f c . . 
        . . c f f f f f f f f f f c . . 
        . . c f f f f f f f f f f c . . 
        . . c f f f f f f f f f f c . . 
        . . c f f f f f f f f f f c . . 
        . c c f f f f f f f f f f c . . 
        c c f f f f f f f f f f f c . . 
        c f f f f f f f f f f f f c . . 
        f f f f f c c c c c c c c c . . 
        f f f f c c . . . . . . . . . . 
        f f f c c . . . . . . . . . . . 
        `)
    tiles.placeOnTile(spelare, tiles.getTileLocation(4, 1))
    if (antal_skott == 1) {
        multiSkott = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . 2 . . . . . 2 . . . . . . . 
            . f 2 f . . . f 2 f . . . . . . 
            . f f f . . . f f f . . . . . . 
            . f f f . . . f f f . . . . . . 
            . f f f . . . f f f . . . . . . 
            . f f f . . . f f f . . . . . . 
            . f f f . 2 . f f f . . . . . . 
            . f f f f 2 f f f f . . . . . . 
            . f f f f f f f f f . . . . . . 
            . . . f f f f f . . . . . . . . 
            . . . f f f f f . . . . . . . . 
            . . . . f f f f . . . . . . . . 
            . . . f f f f f . . . . . . . . 
            . . . . f f f . . . . . . . . . 
            . . . . f f f . . . . . . . . . 
            `, SpriteKind.shopItem)
        tiles.placeOnTile(multiSkott, tiles.getTileLocation(1, 4))
    }
    rainbow = sprites.create(img`
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        2 5 5 5 5 5 5 5 5 5 5 5 5 5 2 2 
        2 5 4 4 4 4 4 4 4 4 4 4 4 5 2 2 
        2 5 4 2 2 2 2 2 2 2 2 2 4 5 2 2 
        2 5 4 2 a a a a a a a 2 4 5 2 2 
        2 5 4 2 a 8 8 8 8 8 a 2 4 5 2 2 
        2 5 4 2 a 8 6 6 6 8 a 2 4 5 2 2 
        2 5 4 2 a 8 6 9 6 8 a 2 4 5 2 2 
        2 5 4 2 a 8 6 6 6 8 a 2 4 5 2 2 
        2 5 4 2 a 8 8 8 8 8 a 2 4 5 2 2 
        2 5 4 2 a a a a a a a 2 4 5 2 2 
        2 5 4 2 2 2 2 2 2 2 2 2 4 5 2 2 
        2 5 4 4 4 4 4 4 4 4 4 4 4 5 2 2 
        2 5 5 5 5 5 5 5 5 5 5 5 5 5 2 2 
        2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 
        `, SpriteKind.shopItem)
    tiles.placeOnTile(rainbow, tiles.getTileLocation(8, 1))
    heal = sprites.create(img`
        . . . . . . . . e e e . . . . . 
        . . . . . . . e e e . . . . . . 
        . . . . . . . e e e . . . . . . 
        . . . . . . e e e . . . . . . . 
        . 2 2 2 2 2 2 f f 2 2 2 2 2 2 . 
        . 2 4 4 4 4 4 f f 4 4 4 4 4 2 . 
        . 2 4 5 5 5 5 f f 5 5 5 5 4 2 . 
        . 2 4 5 3 3 3 f f 3 3 3 5 4 2 . 
        . 2 4 5 3 6 6 f f 6 6 3 5 4 2 . 
        . 2 4 5 3 6 9 f f 9 6 3 5 4 2 . 
        . 2 4 5 3 6 6 f f 6 6 3 5 4 2 . 
        . 2 4 5 3 3 3 f f 3 3 3 5 4 2 . 
        . 2 4 5 5 5 5 f f 5 5 5 5 4 2 . 
        . 2 4 4 4 4 4 f f 4 4 4 4 4 2 . 
        . 2 2 2 2 2 2 f f 2 2 2 2 2 2 . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.shopItem)
    tiles.placeOnTile(heal, tiles.getTileLocation(9, 4))
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile29`, function (sprite, location) {
    info.startCountdown(90)
    bana = 1
    tiles.setCurrentTilemap(tilemap`level26`)
    tiles.placeOnTile(spelare, tiles.getTileLocation(8, 10))
})
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    sprites.destroy(status.spriteAttachedTo())
})
sprites.onOverlap(SpriteKind.Regnbåge, SpriteKind.Enemy, function (sprite, otherSprite) {
    statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, otherSprite).value += -1000
    info.changeScoreBy(1)
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    game.setGameOverMessage(false, convertToText(info.countdown()))
    game.gameOver(false)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bana == 3) {
        animation.runImageAnimation(
        spelare,
        [img`
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . f f e e 4 4 4 e f . . . 
            . . . . . 4 d d e 2 2 2 f . . . 
            . . . . . e d d e 2 2 2 f . . . 
            . . . . . f e e f 4 5 5 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . f f f . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e e e d d d f . . . 
            . . . . . f 4 d d e 4 e f . . . 
            . . . . . f e d d e 2 2 f . . . 
            . . . . f f f e e f 5 5 f f . . 
            . . . . f f f f f f f f f f . . 
            . . . . . f f . . . f f f . . . 
            `,img`
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . f f e e 4 4 4 e f . . . 
            . . . . . 4 d d e 2 2 2 f . . . 
            . . . . . e d d e 2 2 2 f . . . 
            . . . . . f e e f 4 5 5 f . . . 
            . . . . . . f f f f f f . . . . 
            . . . . . . . f f f . . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f f f . . . . 
            . . . . f f e e e e f 2 f . . . 
            . . . f f e e e e f 2 2 2 f . . 
            . . . f e e e f f e e e e f . . 
            . . . f f f f e e 2 2 2 2 e f . 
            . . . f e 2 2 2 f f f f e 2 f . 
            . . f f f f f f f e e e f f f . 
            . . f f e 4 4 e b f 4 4 e e f . 
            . . f e e 4 d 4 1 f d d e f . . 
            . . . f e e e 4 d d d d f . . . 
            . . . . 4 d d e 4 4 4 e f . . . 
            . . . . e d d e 2 2 2 2 f . . . 
            . . . . f e e f 4 4 5 5 f f . . 
            . . . . f f f f f f f f f f . . 
            . . . . . f f . . . f f f . . . 
            `],
        100,
        false
        )
        if (controller.A.isPressed()) {
            controller.moveSprite(spelare, 0, 0)
            if (spelare.isHittingTile(CollisionDirection.Left)) {
            	
            } else {
                svärd.setImage(img`
                    ..........................
                    ..........................
                    ..........................
                    ............ccccc.........
                    ......ff.ccccdddccc.......
                    ff....ffccdddddddddccc....
                    ffeeeeffdddddddddddddccc..
                    ffeeeeffddddddddddccccccc.
                    ff....ffccccccccccc.......
                    ......ff..................
                    ..........................
                    ..........................
                    ..........................
                    ..........................
                    ..........................
                    ..........................
                    `)
                svärd.setPosition(spelare.x + 22, spelare.y + 3)
                pause(100)
                svärd.x += 8
                pause(100)
                svärd.x += -8
                pause(100)
                svärd.setImage(img`
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    . . . . . . . . . . . . . . . . 
                    `)
            }
        }
    }
})
controller.A.onEvent(ControllerButtonEvent.Released, function () {
    if (bana == 3) {
        controller.moveSprite(spelare)
    }
})
sprites.onOverlap(SpriteKind.Enemy, SpriteKind.Player, function (sprite, otherSprite) {
    spelare_HP.value += -5
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile57`, function (sprite, location) {
    tiles.placeOnTile(spelare, tiles.getTileLocation(33, 97))
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile52`, function (sprite, location) {
    tiles.placeOnTile(spelare, tiles.getTileLocation(33, 97))
})
controller.down.onEvent(ControllerButtonEvent.Pressed, function () {
    if (bana == 3) {
        animation.runImageAnimation(
        spelare,
        [img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . f f e 2 f f f f f f 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f . . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . . f e 4 d d d d 4 e f e . . 
            . . f e f 2 2 2 2 e d d 4 e . . 
            . . e 4 f 2 2 2 2 e d d e . . . 
            . . . . f 4 4 5 5 f e e . . . . 
            . . . . f f f f f f f . . . . . 
            . . . . f f f . . . . . . . . . 
            `,img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `,img`
            . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f e e 2 2 2 2 2 2 e f f . . 
            . f f e 2 f f f f f f 2 e f f . 
            . f f f f f e e e e f f f f f . 
            . . f e f b f 4 4 f b f e f . . 
            . . f e 4 1 f d d f 1 4 e f . . 
            . . e f e 4 d d d d 4 e f . . . 
            . . e 4 d d e 2 2 2 2 f e f . . 
            . . . e d d e 2 2 2 2 f 4 e . . 
            . . . . e e f 5 5 4 4 f . . . . 
            . . . . . f f f f f f f . . . . 
            . . . . . . . . . f f f . . . . 
            `],
        100,
        false
        )
        if (controller.A.isPressed()) {
            controller.moveSprite(spelare, 0, 0)
            if (spelare.isHittingTile(CollisionDirection.Left)) {
            	
            } else {
                svärd.setImage(img`
                    .......ffff.....
                    .......ffff.....
                    ........ee......
                    ........ee......
                    ........ee......
                    ........ee......
                    ......ffffff....
                    ......ffffff....
                    .......cddc.....
                    .......cddcc....
                    .......cdddc....
                    .......cdddc....
                    .......cdddcc...
                    .......cddddc...
                    .......cddddc...
                    .......cddddc...
                    .......cdddcc...
                    .......cdddc....
                    .......ccddc....
                    ........cdc.....
                    ........cdc.....
                    ........ccc.....
                    ........cc......
                    ........cc......
                    ........c.......
                    ................
                    `)
                svärd.setPosition(spelare.x, spelare.y + 22)
            }
            pause(100)
            svärd.y += 8
            pause(100)
            svärd.y += -8
            pause(100)
            svärd.setImage(img`
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `)
        }
    }
})
scene.onOverlapTile(SpriteKind.Player, sprites.castle.tileGrass2, function (sprite, location) {
    if (bana == 0) {
        bana = 3
        tiles.setCurrentTilemap(tilemap`level36`)
        spelare = sprites.create(img`
            . . . . . . f f f f . . . . . . 
            . . . . f f f 2 2 f f f . . . . 
            . . . f f f 2 2 2 2 f f f . . . 
            . . f f f e e e e e e f f f . . 
            . . f f e 2 2 2 2 2 2 e e f . . 
            . . f e 2 f f f f f f 2 e f . . 
            . . f f f f e e e e f f f f . . 
            . f f e f b f 4 4 f b f e f f . 
            . f e e 4 1 f d d f 1 4 e e f . 
            . . f e e d d d d d d e e f . . 
            . . . f e e 4 4 4 4 e e f . . . 
            . . e 4 f 2 2 2 2 2 2 f 4 e . . 
            . . 4 d f 2 2 2 2 2 2 f d 4 . . 
            . . 4 4 f 4 4 5 5 4 4 f 4 4 . . 
            . . . . . f f f f f f . . . . . 
            . . . . . f f . . f f . . . . . 
            `, SpriteKind.Player)
        svärd = sprites.create(img`
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            . . . . . . . . . . . . . . . . 
            `, SpriteKind.svärd)
        tiles.placeOnTile(spelare, tiles.getTileLocation(8, 13))
        controller.moveSprite(spelare)
        scene.cameraFollowSprite(spelare)
        list = []
        list3 = []
        bana3_enemy_speed = 10
    }
})
sprites.onOverlap(SpriteKind.svärd, SpriteKind.Enemy, function (sprite, otherSprite) {
    if (bana == 3) {
        sprites.destroy(otherSprite)
        info.changeScoreBy(1)
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile62`, function (sprite, location) {
    tiles.placeOnTile(spelare, tiles.getTileLocation(6, 38))
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`myTile51`, function (sprite, location) {
    if (controller.A.isPressed()) {
        if (spelare.tilemapLocation().column == location.column) {
            spelare.setVelocity(0, -100)
        }
    }
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    statusbars.getStatusBarAttachedTo(StatusBarKind.EnemyHealth, otherSprite).value += -111
    sprites.destroy(sprite)
    info.changeScoreBy(1)
})
let regnbåge = 0
let random_calc_y = 0
let random_calc_x = 0
let list2: Sprite[] = []
let bomb: Sprite = null
let bana3_enemy_speed = 0
let list3: number[] = []
let list: Sprite[] = []
let projektil3: Sprite = null
let projektil2: Sprite = null
let projectile: Sprite = null
let enemyStatusBar: StatusBarSprite = null
let enemyList: Sprite[] = []
let shop = 0
let svärd: Sprite = null
let attack_regnbåge: Sprite = null
let heal: Sprite = null
let rainbow: Sprite = null
let multiSkott: Sprite = null
let antal_skott = 0
let spelare_HP: StatusBarSprite = null
let spelare: Sprite = null
let xoffset = 0
let bana = 0
let aliveList: Sprite[] = []
let regnbåge_tillgänglig = 0
regnbåge_tillgänglig = 0
aliveList = []
bana = 0
xoffset = 22
spelare = sprites.create(img`
    . . . . . . 1 1 . . . . . . 
    f . f . . 1 1 1 1 . . f . f 
    f 2 f . 1 1 1 1 1 1 . f 2 f 
    f 2 f . 1 1 5 5 1 1 . f 2 f 
    f 2 f . 1 1 1 1 1 1 . f 2 f 
    f f f . 1 1 5 5 1 1 . f f f 
    f f f . 1 1 1 1 1 1 . f f f 
    f f f f 1 1 1 1 1 1 f f f f 
    f f f f 1 1 5 5 1 1 f f f f 
    f f f f 2 1 1 1 1 2 f f f f 
    . . f f 1 1 1 1 1 1 f f . . 
    . . . f 1 1 1 1 1 1 f . . . 
    . . . . 1 1 1 1 1 1 . . . . 
    . . . 1 1 1 1 1 1 1 1 . . . 
    . . 1 1 2 2 2 2 2 2 1 1 . . 
    . . . . 2 2 2 2 2 2 . . . . 
    . . . 2 2 2 2 2 2 2 2 . . . 
    . . . 2 2 2 2 2 2 2 2 . . . 
    . . 2 2 2 2 2 2 2 2 2 2 . . 
    `, SpriteKind.Player)
spelare_HP = statusbars.create(20, 4, StatusBarKind.Health)
spelare_HP.attachToSprite(spelare)
controller.moveSprite(spelare)
scene.cameraFollowSprite(spelare)
tiles.setCurrentTilemap(tilemap`level10`)
tiles.placeOnTile(spelare, tiles.getTileLocation(14, 33))
antal_skott = 1
game.onUpdateInterval(2000, function () {
    impossible()
})
game.onUpdateInterval(2000, function () {
    for (let value of aliveList) {
        if (randint(1, 5) == 1) {
            bomb = sprites.createProjectileFromSprite(img`
                . . . . . f . 
                . . . . . f . 
                . . . f f . . 
                . . . f . . . 
                . . . f . . . 
                . . . f . . . 
                . . . f . . . 
                f f f f f f f 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                2 f 2 f 2 f 2 
                `, value, 0, 50)
            bomb.setKind(SpriteKind.hostileProjectile)
        }
        if (value.y >= 180) {
            for (let index = 0; index < 9; index++) {
                sprites.destroy(aliveList.shift())
            }
        }
    }
})
game.onUpdateInterval(3500, function () {
    if (bana == 3) {
        list2 = [sprites.create(img`
            ...ff..............ff.....
            ...fff............fff.....
            ....fff.ff.f.fff.fff......
            .....ffffffffffffff.......
            ......f2222ff2222f........
            .....ff2222ff2222ff.......
            .....ff2222ff2222ff.......
            ......f2222ff2222f........
            .....f2ffffffffff2f.......
            ......f2ffffffff2f........
            .....fff22222222fff.......
            ....ffffffffffffffff......
            ....ffffffffffffffff......
            ....ffffffffffffffff......
            ....ffffffffffffffff......
            ....ffffff2222ffffff......
            ....fffff2c2c22fffff......
            ....fffff2222c2fffff......
            ....fffff2c222cfffff......
            ....fffff2c2c22fffff......
            ....ffffff.2c2ffffff......
            ....ffffff....ffffff......
            ....ffffff....ffffff......
            ....ffffff....ffffff......
            ....fcffcf....fcffcf......
            ....fcffcf....fcffcf......
            `, SpriteKind.Enemy)]
        list.push(list2[0])
        random_calc_x = randint(1, 2)
        random_calc_y = randint(1, 2)
        if (random_calc_x == 2) {
            random_calc_x = -1
        }
        if (random_calc_y == 2) {
            random_calc_y = -1
        }
        tiles.placeOnTile(list[list.length - 1], tiles.getTileLocation(spelare.tilemapLocation().column + random_calc_x * randint(2, 3), spelare.tilemapLocation().row + random_calc_y * randint(2, 3)))
        sprites.create(img`
            ...ff..............ff.....
            ...fff............fff.....
            ....fff.ff.f.fff.fff......
            .....ffffffffffffff.......
            ......f2222ff2222f........
            .....ff2222ff2222ff.......
            .....ff2222ff2222ff.......
            ......f2222ff2222f........
            .....f2ffffffffff2f.......
            ......f2ffffffff2f........
            .....fff22222222fff.......
            ....ffffffffffffffff......
            ....ffffffffffffffff......
            ....ffffffffffffffff......
            ....ffffffffffffffff......
            ....ffffff2222ffffff......
            ....fffff2c2c22fffff......
            ....fffff2222c2fffff......
            ....fffff2c222cfffff......
            ....fffff2c2c22fffff......
            ....ffffff.2c2ffffff......
            ....ffffff....ffffff......
            ....ffffff....ffffff......
            ....ffffff....ffffff......
            ....fcffcf....fcffcf......
            ....fcffcf....fcffcf......
            `, SpriteKind.Enemy).setFlag(SpriteFlag.GhostThroughWalls, false)
        if (list[list.length - 1].tileKindAt(TileDirection.Center, sprites.builtin.forestTiles0)) {
            sprites.destroy(list[list.length - 1])
        }
        list[list.length - 1].follow(spelare, bana3_enemy_speed)
        if (spelare.y >= list[list.length - 1].y) {
            animation.runImageAnimation(
            list[list.length - 1],
            [img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffff2222ffffff......
                ....fffff2c2c22fffff......
                ....fffff2222c2fffff......
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....fcffcf....fcffcf......
                ....fcffcf....fcffcf......
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                ...ffffff2222c2ffffff.....
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....fcffcf....fcffcf......
                ....fcffcf....fcffcf......
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ...fffffff2222fffffff.....
                ..fffffff2c2c22fffffff....
                ...ffffff2222c2ffffff.....
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ....fcffcf....fcffcf......
                ....fcffcf....fcffcf......
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                ..ffffffff2222ffffffff....
                ..fffffff2c2c22fffffff....
                ...ffffff2222c2ffffff.....
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....fcffcf.2c2fcffcf......
                ....fcffcf....fcffcf......
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                .ffffffffffffffffffffff...
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                ....fffff2222c2fffff......
                ....fffff2c222cfffff......
                ....fcffc2c2c22cffcf......
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                ffffffffffffffffffffffff..
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                ....fffff2222c2fffff......
                ....fcffc2c222ccffcf......
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                .....fff22222222fff.......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                .ffffffffffffffffffffff...
                ffffffffffffffffffffffff..
                .fffffffff2222fffffffff...
                ...ffffff2c2c22ffffff.....
                ....fffff2222c2fffff......
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ......f2ffffffff2f........
                ...fcfff22222222fffcf.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                ffffffffffffffffffffffff..
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                .....ff2222ff2222ff.......
                ......f2222ff2222f........
                .....f2ffffffffff2f.......
                ...fcff2ffffffff2ffcf.....
                ...fcfff22222222fffcf.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                .ffffffffffffffffffffff...
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                .....ff2222ff2222ff.......
                ...fcff2222ff2222ffcf.....
                ...fcff2222ff2222ffcf.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                ..ffffffffffffffffffff....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......f2222ff2222f........
                ...fcff2222ff2222ffcf.....
                ...fcff2222ff2222ffcf.....
                ...ffff2222ff2222ffff.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ...fcff2222ff2222ffcf.....
                ...fcff2222ff2222ffcf.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                ...fcffffffffffffffcf.....
                ...fcff2222ff2222ffcf.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ...fcff.ff.f.fff.ffcf.....
                ...fcffffffffffffffcf.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                ...fcffffffffffffffcf.....
                ...fcff2222ff2222ffcf.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ...fcff2222ff2222ffcf.....
                ...fcff2222ff2222ffcf.....
                ...ffff2222ff2222ffff.....
                ...ffff2222ff2222ffff.....
                ...fff2ffffffffff2fff.....
                ...ffff2ffffffff2ffff.....
                ...fffff22222222fffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `],
            500,
            false
            )
        } else if (spelare.y < list[list.length - 1].y) {
            animation.runImageAnimation(
            list[list.length - 1],
            [img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffff2222ffffff......
                ....fffff2c2c22fffff......
                ....fffff2222c2fffff......
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                ...ffffff2222c2ffffff.....
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ...fffffff2222fffffff.....
                ..fffffff2c2c22fffffff....
                ...ffffff2222c2ffffff.....
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ....ffffff....ffffff......
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                ..ffffffff2222ffffffff....
                ..fffffff2c2c22fffffff....
                ...ffffff2222c2ffffff.....
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ....ffffff.2c2ffffff......
                ....ffffff....ffffff......
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                .ffffffffffffffffffffff...
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                ....fffff2222c2fffff......
                ....fffff2c222cfffff......
                ....fffff2c2c22fffff......
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                ffffffffffffffffffffffff..
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                ....fffff2222c2fffff......
                ....fffff2c222cfffff......
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ....ffffffffffffffff......
                ...ffffffffffffffffff.....
                .ffffffffffffffffffffff...
                ffffffffffffffffffffffff..
                .fffffffff2222fffffffff...
                ...ffffff2c2c22ffffff.....
                ....fffff2222c2fffff......
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ......ffffffffffff........
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                ffffffffffffffffffffffff..
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                .ffffffffffffffffffffff...
                ..ffffffff2222ffffffff....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                .....ffffffffffffff.......
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ..ffffffffffffffffffff....
                ..ffffffffffffffffffff....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ......ffffffffffff........
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ...ffff.ff.f.fff.ffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                .........2c2c22...........
                ...........2c2............
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `,img`
                ...ff..............ff.....
                ...fff............fff.....
                ....fff.ff.f.fff.fff......
                .....ffffffffffffff.......
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...ffffffffffffffffff.....
                ...fffffff2222fffffff.....
                ...ffffff2c2c22ffffff.....
                .........2222c2...........
                .........2c222c...........
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                ..........................
                `],
            500,
            false
            )
        }
        bana3_enemy_speed += 5
    }
})
game.onUpdateInterval(100, function () {
    if (regnbåge == 1) {
        let attack_regnbåge_bakgrund: Sprite = null
        attack_regnbåge_bakgrund.changeScale(1, ScaleAnchor.Middle)
        if (attack_regnbåge_bakgrund.isHittingTile(CollisionDirection.Left) || (attack_regnbåge_bakgrund.isHittingTile(CollisionDirection.Top) || (attack_regnbåge_bakgrund.isHittingTile(CollisionDirection.Right) || attack_regnbåge_bakgrund.isHittingTile(CollisionDirection.Bottom)))) {
            sprites.destroy(attack_regnbåge)
            sprites.destroy(attack_regnbåge_bakgrund)
            regnbåge = 0
        }
    }
})
